font_path: "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
font_size: 14
line_height: 20
padding: [10, 10]
bg_color: "rgb(15,15,15)"
text_color: "rgb(220,220,220)"
save_path: "/tmp/testing.png"

max_image_width: 800
max_image_height: 500